# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StudyBuddyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftUIPager'
  pod 'SwiftySound'


  # Pods for StudyBuddyApp

  target 'StudyBuddyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StudyBuddyAppUITests' do
    # Pods for testing
  end

end
